//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace UnblockUSTest
{
}

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NetflixConfig {
    
    private string device_supportedField;
    
    private string countryField;
    
    private string enable_content_header_cacheField;
    
    private string nctsField;
    
    private string stall_notification_intrplayField;
    
    private string geolocationlocaleField;
    
    private string movie_norminal_to_peak_bandwidth_multiplierField;
    
    private string movie_peakbandwidth_multiplierField;
    
    private string instant_queue_enabledField;
    
    private string showDDField;
    
    private string geolocationasnField;
    
    private string geolocationinternal_networkField;
    
    private string support_assistive_audioField;
    
    private string connection_timeout_slowField;
    
    private string geolocationstatusField;
    
    private string prefetch_timeout_in_secondsField;
    
    private string manifest_expiration_in_secondsField;
    
    private string geolocationcountryField;
    
    private string connection_retriesField;
    
    private string header_downloader_cache_sizeField;
    
    private string movie_iframe_bandwidth_multiplierField;
    
    private string cdn_open_connect_forcedField;
    
    private string initial_bitrate_mask_wifiField;
    
    private string support_title_audio_selectionField;
    
    private string selected_cdn_bandwidth_multiplierField;
    
    private string geolocationlanguageField;
    
    private string dvd_service_allowedField;
    
    private string dd_5_1_enabledField;
    
    private string min_cticket_renew_secondsField;
    
    private string connection_timeoutField;
    
    private string use_dash_profilesField;
    
    private string generic_feed_urlField;
    
    private string geolocationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string device_supported {
        get {
            return this.device_supportedField;
        }
        set {
            this.device_supportedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string enable_content_header_cache {
        get {
            return this.enable_content_header_cacheField;
        }
        set {
            this.enable_content_header_cacheField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ncts {
        get {
            return this.nctsField;
        }
        set {
            this.nctsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stall_notification_intrplay {
        get {
            return this.stall_notification_intrplayField;
        }
        set {
            this.stall_notification_intrplayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("geolocation.locale", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string geolocationlocale {
        get {
            return this.geolocationlocaleField;
        }
        set {
            this.geolocationlocaleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string movie_norminal_to_peak_bandwidth_multiplier {
        get {
            return this.movie_norminal_to_peak_bandwidth_multiplierField;
        }
        set {
            this.movie_norminal_to_peak_bandwidth_multiplierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string movie_peakbandwidth_multiplier {
        get {
            return this.movie_peakbandwidth_multiplierField;
        }
        set {
            this.movie_peakbandwidth_multiplierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string instant_queue_enabled {
        get {
            return this.instant_queue_enabledField;
        }
        set {
            this.instant_queue_enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string showDD {
        get {
            return this.showDDField;
        }
        set {
            this.showDDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("geolocation.asn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string geolocationasn {
        get {
            return this.geolocationasnField;
        }
        set {
            this.geolocationasnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("geolocation.internal_network", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string geolocationinternal_network {
        get {
            return this.geolocationinternal_networkField;
        }
        set {
            this.geolocationinternal_networkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string support_assistive_audio {
        get {
            return this.support_assistive_audioField;
        }
        set {
            this.support_assistive_audioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string connection_timeout_slow {
        get {
            return this.connection_timeout_slowField;
        }
        set {
            this.connection_timeout_slowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("geolocation.status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string geolocationstatus {
        get {
            return this.geolocationstatusField;
        }
        set {
            this.geolocationstatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string prefetch_timeout_in_seconds {
        get {
            return this.prefetch_timeout_in_secondsField;
        }
        set {
            this.prefetch_timeout_in_secondsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string manifest_expiration_in_seconds {
        get {
            return this.manifest_expiration_in_secondsField;
        }
        set {
            this.manifest_expiration_in_secondsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("geolocation.country", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string geolocationcountry {
        get {
            return this.geolocationcountryField;
        }
        set {
            this.geolocationcountryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string connection_retries {
        get {
            return this.connection_retriesField;
        }
        set {
            this.connection_retriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string header_downloader_cache_size {
        get {
            return this.header_downloader_cache_sizeField;
        }
        set {
            this.header_downloader_cache_sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string movie_iframe_bandwidth_multiplier {
        get {
            return this.movie_iframe_bandwidth_multiplierField;
        }
        set {
            this.movie_iframe_bandwidth_multiplierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cdn_open_connect_forced {
        get {
            return this.cdn_open_connect_forcedField;
        }
        set {
            this.cdn_open_connect_forcedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string initial_bitrate_mask_wifi {
        get {
            return this.initial_bitrate_mask_wifiField;
        }
        set {
            this.initial_bitrate_mask_wifiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string support_title_audio_selection {
        get {
            return this.support_title_audio_selectionField;
        }
        set {
            this.support_title_audio_selectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string selected_cdn_bandwidth_multiplier {
        get {
            return this.selected_cdn_bandwidth_multiplierField;
        }
        set {
            this.selected_cdn_bandwidth_multiplierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("geolocation.language", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string geolocationlanguage {
        get {
            return this.geolocationlanguageField;
        }
        set {
            this.geolocationlanguageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dvd_service_allowed {
        get {
            return this.dvd_service_allowedField;
        }
        set {
            this.dvd_service_allowedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dd_5_1_enabled {
        get {
            return this.dd_5_1_enabledField;
        }
        set {
            this.dd_5_1_enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string min_cticket_renew_seconds {
        get {
            return this.min_cticket_renew_secondsField;
        }
        set {
            this.min_cticket_renew_secondsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string connection_timeout {
        get {
            return this.connection_timeoutField;
        }
        set {
            this.connection_timeoutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string use_dash_profiles {
        get {
            return this.use_dash_profilesField;
        }
        set {
            this.use_dash_profilesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string generic_feed_url {
        get {
            return this.generic_feed_urlField;
        }
        set {
            this.generic_feed_urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string geolocation {
        get {
            return this.geolocationField;
        }
        set {
            this.geolocationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NetflixDataSet {
    
    private NetflixConfig[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("config")]
    public NetflixConfig[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

namespace UnblockUSTest
{


    partial class NewDataSet
    {
    }
}
